on:
  push:
    branches: [ main ]

name: kubernetes cluster

jobs:

  Deployto_kubecluster:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    -  name: Setup kubectl
       id: install-kubectl
       uses: azure/setup-kubectl@v3
        
    - name: Running kube clusters
      shell: bash
      run: | 
        
        az aks get-credentials --resource-group dev-rg --name testkubernetcluster01

        kubectl version

        kubectl get pods

        kubectl apply -f deployment.yaml
 
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          
