on:
  push:
    branches: [ main ]

name: kubernetes-cluster

jobs:

  Deployto_kubecluster:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    -  name: Setup kubectl
       id: install-kubectl
       uses: azure/setup-kubectl@v3

    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
    #- name: Update kube config
     # run: az aks get-credentials --resource-group learnk8sResourceGroup --name learnk8scluster
       inlineScript: az aks get-credentials --resource-group learnk8sResourceGroup --name learnk8scluster
        kubectl apply -f menifest\deployment.yaml
    #- name: Deploy image to Amazon EKS
     # run: 
      #   kubectl apply -f menifest\deployment.yaml
        # kubectl apply -f menifest\service.yaml
#
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          
